### ISSUE TITLE
bedpetobed12 pipe fail

### ISSUE THREAD

**Issue by crazyhottommy** [hall-lab/svtools#161]
Hi I am testing svtools v0.2.0

```
svtools bedpetobed12 -b my.bedpe -n mybedpe -d 100000 
```
works.

but when I pipe it to `head`, it shows error in the end

```
svtools bedpetobed12 -b my.bedpe -n mybedpe -d 100000 | head
track name=mybedpe itemRgb=On
1	963984	964454	DEL;ID=4	357.57	+	963984	964454	153,0,0	2	172,253	0,217
1	1608930	1627731	DEL;ID=23	13.89	+	1608930	1627731	153,0,0	2	230,220	0,18581
1	2523774	2524124	DEL;ID=49	322.43	+	2523774	2524124	153,0,0	2	270,275	0,75
1	4247876	4248134	INV;ID=105	137.24	+	4247876	4248134	0,51,204	2	9,19	0,239
1	4252537	4252808	INV;ID=106	520.46	+	4252537	4252808	0,51,204	2	19,19	0,252
1	4301596	4301615	BND;ID=116;STR=--	200.62	-	4301596	4301615	204,204,204
1	4301766	4301785	BND;ID=116;STR=--	200.62	-	4301766	4301785	204,204,204
1	4309900	4309919	BND;ID=120;STR=++	242.16	+	4309900	4309919	204,204,204
1	4310114	4310132	BND;ID=120;STR=++	242.16	+	4310114	4310132	204,204,204
Traceback (most recent call last):
  File "/Users/mtang1/.pyenv/versions/2.7.11/bin/svtools", line 9, in <module>
    load_entry_point('svtools==0.2.0', 'console_scripts', 'svtools')()
  File "/Users/mtang1/.pyenv/versions/2.7.11/lib/python2.7/site-packages/svtools/cli.py", line 73, in main
    sys.exit(args.entry_point(args))
  File "/Users/mtang1/.pyenv/versions/2.7.11/lib/python2.7/site-packages/svtools/bedpetobed12.py", line 206, in run_from_args
    processBEDPE(stream, args.name, args.dist)
  File "/Users/mtang1/.pyenv/versions/2.7.11/lib/python2.7/site-packages/svtools/bedpetobed12.py", line 185, in processBEDPE
    output_handle.write('\n'.join(converter.convert(bedpe)) + '\n')
IOError: [Errno 32] Broken pipe
```

Best,
Tommy

**Comment by ernfrid** [comment]
Rats. I thought I had gotten all those, but I guess I missed at least one. This is the result of poor handling of when a pipe terminates normally. You can ignore the error message. Your results should be fine.

**Comment by crazyhottommy** [comment]
Thanks!
