### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by atasub** [hall-lab/svtools#193]
Hi,

when I tried to run vcftobedpe analysis, got a constant error like this: 

Traceback (most recent call last):
  File "/Users/burcudursun/miniconda2/bin/svtools", line 6, in <module>
    sys.exit(svtools.cli.main())
  File "/Users/burcudursun/miniconda2/lib/python2.7/site-packages/svtools-0.3.1-py2.7.egg/svtools/cli.py", line 78, in main
  File "/Users/burcudursun/miniconda2/lib/python2.7/site-packages/svtools-0.3.1-py2.7.egg/svtools/vcftobedpe.py", line 120, in run_from_args
  File "/Users/burcudursun/miniconda2/lib/python2.7/site-packages/svtools-0.3.1-py2.7.egg/svtools/vcftobedpe.py", line 67, in vcfToBedpe
  File "/Users/burcudursun/miniconda2/lib/python2.7/site-packages/svtools-0.3.1-py2.7.egg/svtools/vcf/variant.py", line 35, in __init__
IndexError: list index out of range

Could you please help me to solve this?

**Comment by ernfrid** [comment]
My best guess based on that error message is that your input VCF doesn't include sample information (i.e. a format field and samples). Is that correct?
