### ISSUE TITLE
Lmerge (KeyError: 'PRPOS' )

### ISSUE THREAD

**Issue by MehmetGoktay** [hall-lab/svtools#240]
Hi,

I follow svtool tutorial but when I do Lmerge step, I have this error. 

Traceback (most recent call last):
  File "/home/goktay/miniconda2/bin/svtools", line 6, in <module>
    sys.exit(svtools.cli.main())
  File "/home/goktay/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/cli.py", line 78, in main
  File "/home/goktay/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/lmerge.py", line 632, in run_from_args
  File "/home/goktay/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/lmerge.py", line 583, in l_cluster_by_line
  File "/home/goktay/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/breakpoint.py", line 24, in __init__
KeyError: 'PRPOS'

What I have done till this step: 

called svs using lumpyexpress per sample and genotyped with svtyper per sample individually.

Then first command is : svtools lsort 12761.svtyper.vcf 12762.svtyper.vcf | bgzip -c > sorted.vcf.gz

and second command is : zcat sorted.vcf.gz | svtools lmerge -i /dev/stdin -f 20  | bgzip -c > merged.vcf.gz

But I keep getting same error. 

Could you please help me with this error?

Mehmet

**Comment by ernfrid** [comment]
lmerge requires that lumpy was run with the -P option to report breakpoint probabilities. If it was not run in this fashion then it will need to be re-run with the options


The relevant note in the tutorial is:


Note: Make certain to run speedseq sv using the following options: -v -d -P -g -k option as subsequent steps will utilize CNVnator files in the temporary directories, assume that SVTyper has been run and require LUMPY's probability curves.

I've made a note to improve the error message for this situation.

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Comment by MehmetGoktay** [comment]
Yes I did not used -P parameter.

 Thank you for pointing out.
