### ISSUE TITLE
svtools lmerge error 

### ISSUE THREAD

**Issue by jjfarrell** [hall-lab/svtools#255]
Any suggestions for the following error.  This is being run to create input for SVTyper. The input file was created with svtools lsort.

svtools lmerge -i gcad.5k.sort.txt >gcad.5k.sites.merge.txt
```
Traceback (most recent call last):
  File "/usr3/bustaff/farrell/anaconda_envs/bioinformatics/bin/svtools", line 6, in <module>
    sys.exit(svtools.cli.main())
  File "/usr3/bustaff/farrell/anaconda_envs/bioinformatics/lib/python2.7/site-packages/svtools/cli.py", line 73, in main
    sys.exit(args.entry_point(args))
  File "/usr3/bustaff/farrell/anaconda_envs/bioinformatics/lib/python2.7/site-packages/svtools/lmerge.py", line 598, in run_from_args
    use_product=args.use_product)
  File "/usr3/bustaff/farrell/anaconda_envs/bioinformatics/lib/python2.7/site-packages/svtools/lmerge.py", line 558, in l_cluster_by_line
    b=l_bp.breakpoint(l_bp.parse_vcf_record(l), percent_slop=percent_slop, fixed_slop=fixed_slop)
  File "/usr3/bustaff/farrell/anaconda_envs/bioinformatics/lib/python2.7/site-packages/svtools/l_bp.py", line 70, in parse_vcf_record
    if not 'SECONDARY' in A[7]:
IndexError: list index out of rang
```e

**Comment by ernfrid** [comment]
It looks to me like your input file is not a VCF or is perhaps a VCF without a full complement of columns. For the current released version of svtools, your input to lsort should be a VCF with non-homozygous reference genotypes. The version on the development branch should be able to handle 8 column VCFs if you’re willing to live on the bleeding edge.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jjfarrell** [comment]
svtools lsort 0.3.2  generate the input vcf file for svtools lmerge. 

It looks like this error  did not occur until the end as merge output file contains chrY sites.

**Comment by ernfrid** [comment]
If you provided what you believe to be valid VCFs (with a genotype column) to `lsort` then this suggests to me that one of the input files may be truncated. I would ensure that this isn't the case by checking each input file and ensuring that all non-header lines have at least 10 columns.
