### ISSUE TITLE
IndexError: list index out of range while running lsort

### ISSUE THREAD

**Issue by deepalivasoya** [hall-lab/svtools#256]
Hello,

My workflow is like this: 
1) Running lumpy on 10 samples. 
2) SVTyper using lumpy vcf on each sample
3) lsort SVTyper vcfs
4) lmerge SVTyper vcfs. 

Until SVTyper everything was okay. I am getting error while running lsort. 
Traceback (most recent call last):
  File "/software/deepali/anaconda3_5.0/envs/sv/bin/svtools", line 6, in <module>
    sys.exit(svtools.cli.main())
  File "build/bdist.linux-x86_64/egg/svtools/cli.py", line 78, in main
  File "build/bdist.linux-x86_64/egg/svtools/lsort.py", line 118, in run_from_args
  File "build/bdist.linux-x86_64/egg/svtools/lsort.py", line 44, in execute
  File "build/bdist.linux-x86_64/egg/svtools/l_bp.py", line 31, in parse_vcf
IndexError: list index out of range

I have checked vcf files and they have 10 columns
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BO2660(my sample name)

I am not sure where it went wrong. Thank you.

**Comment by ernfrid** [comment]
I believe that error indicates that there is a line missing a FORMAT field. It's trying to check if the line has a GT field specified, but it looks like there isn't a 9th column.

Did you check every line of your input VCFs? Or just the header?
