### ISSUE TITLE
svtools Genotype + Key Error: 'END'

### ISSUE THREAD

**Issue by mehar-GIT** [hall-lab/svtools#257]
I have used the svtools protocol at https://github.com/hall-lab/svtools/blob/master/Tutorial.md .  However, i am having the below error while using svtools genotype:

Running svtyper with options: /svtools/bin/svtyper/svtyper --split_weight 1 -n 1000000 --disc_weight 1 -m 20 -B /wrk/proj/hWGS.sorted.bam -l /wrk/proj/recalibrated.bam.json
Reading library metrics from /wrk/proj/recalibrated.bam.json... done
Traceback (most recent call last):
  File "/.my_py_venv/lib/python2.7/site-packages/svtools/bin/svtyper/svtyper", line 1768, in <module>
    sys.exit(main())
  File "/.my_py_venv/lib/python2.7/site-packages/svtools/bin/svtyper/svtyper", line 1763, in main
    args.alignment_outpath)
  File "/.my_py_venv/lib/python2.7/site-packages/svtools/bin/svtyper/svtyper", line 1480, in sv_genotype
    posB = int(var.get_info('END'))
  File "/.my_py_venv/lib/python2.7/site-packages/svtools/bin/svtyper/svtyper", line 215, in get_info
    return self.info[field]
KeyError: 'END'
svtyper exited with code 1

Any tips to fix this are appreciated.

**Comment by ernfrid** [comment]
Your input VCF must have an END tag in the VCF for svtyper to work. If your input file is from `svtools merge` then I'd expect it to exist.
