### ISSUE TITLE
Svtools copynumber error

### ISSUE THREAD

**Issue by deepalivasoya** [hall-lab/svtools#287]
Hello,

I am running svtools to add the copynumber information in vcf. CNVnator is up running and I have created hist root file. Genotyping is also done successfully. In the next step where we add copynumner in genotype, I am having the following issue:

/software/deepali/CNVnator/cnvnator: error while loading shared libraries: libCore.so: wrong ELF class: ELFCLASS32
Traceback (most recent call last):
  File "/software/deepali/anaconda/envs/svtools/bin/svtools", line 11, in <module>
    sys.exit(main())
  File "/software/deepali/anaconda/envs/svtools/lib/python2.7/site-packages/svtools/cli.py", line 78, in main
    sys.exit(args.entry_point(args))
  File "/software/deepali/anaconda/envs/svtools/lib/python2.7/site-packages/svtools/copynumber.py", line 107, in run_from_args
    sv_readdepth(stream, args.sample, args.root, args.window, args.output, args.cnvnator, args.coordinates)
  File "/software/deepali/anaconda/envs/svtools/lib/python2.7/site-packages/svtools/copynumber.py", line 26, in sv_readdepth
    write_copynumber(vcf_file, sample, vcf_out, cn)
  File "/software/deepali/anaconda/envs/svtools/lib/python2.7/site-packages/svtools/copynumber.py", line 77, in write_copynumber
    update_line_copynumber(v, cn_list, i)
  File "/software/deepali/anaconda/envs/svtools/lib/python2.7/site-packages/svtools/copynumber.py", line 32, in update_line_copynumber
    if cn_list[i] == -1:
IndexError: list index out of range
cat: write error: Broken pipe

I have root/5.34.23 installed on server. I dont understand the compiling error while both svtools and cnvnator are working fine on its own. 
It would be great if I get some help asap here. 

Cheers,
Deepali

**Comment by ashwinichhipa** [comment]
Hi Deepali,
I also came across this issue, and updating ROOT to the latest version solved it for me.

Thanks!
