### ISSUE TITLE
No module named 'l_bp'

### ISSUE THREAD

**Issue by Avramis** [hall-lab/svtools#309]
Hi

I installed svtools_v0.5.1 on my mac and when I tried to run it I got the following error message
   
```
   svtools
      Traceback (most recent call last):
        File "/Users/avraam/.pyenv/versions/3.9.2/bin/svtools", line 33, in <module>
          sys.exit(load_entry_point('svtools==0.5.1', 'console_scripts', 'svtools')())
        File "/Users/avraam/.pyenv/versions/3.9.2/bin/svtools", line 25, in importlib_load_entry_point
          return next(matches).load()
        File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/importlib/metadata.py", line 77, in load
          module = import_module(match.group('module'))
        File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 786, in exec_module
        File "<frozen importlib._bootstrap_external>", line 923, in get_code
        File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/site-packages/svtools/cli.py", line 21
          print support_string
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(support_string)?
```

After changing the line 21 in the file ~/svtools/cli.py  
from 
`print support_string`
to
`print (support_string);`

I got the following error message

```
    svtools
    Traceback (most recent call last):
      File "/Users/avraam/.pyenv/versions/3.9.2/bin/svtools", line 33, in <module>
        sys.exit(load_entry_point('svtools==0.5.1', 'console_scripts', 'svtools')())
      File "/Users/avraam/.pyenv/versions/3.9.2/bin/svtools", line 25, in importlib_load_entry_point
        return next(matches).load()
      File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/importlib/metadata.py", line 77, in load
        module = import_module(match.group('module'))
      File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/site-packages/svtools/cli.py", line 3, in <module>
        import svtools.lmerge
      File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/site-packages/svtools/lmerge.py", line 4, in <module>
        from svtools.breakpoint import Breakpoint
      File "/Users/avraam/.pyenv/versions/3.9.2/lib/python3.9/site-packages/svtools/breakpoint.py", line 3, in <module>
        import l_bp
    ModuleNotFoundError: No module named 'l_bp'
```

It seems that the package l_bp is missing.
Any suggestions on how to sort this out?

Thanks
Avraam

**Comment by whelena** [comment]
I have the same issue here.
