### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by anoronh4** [hall-lab/svtools#312]
We are trying to install `svtools` in a docker container using `pip install svtools`. Our docker already has `Python 2.7.13` installed on it. The error we get is quite long and I'm happy to provide the full thing upon request. We get a lot of messages starting with `Error compiling Cython file:` followed by a detailed Traceback, for example:
```
#16 57.57     Error compiling Cython file:
#16 57.57     ------------------------------------------------------------
#16 57.57     ...
#16 57.57             # in two steps:
#16 57.57             #   tmp2 = np.dot(T_mat, alpha)
#16 57.57             #   alpha = tmp2 + np.dot(K, v_mat)
#16 57.57             zgemv("N", &r, &r,
#16 57.57                   &alph, &T_mat[0, 0], &ldt, &alpha[0, 0], &one,
#16 57.57                   &beta, &tmp2[0, 0], &one)
#16 57.57                  ^
#16 57.57     ------------------------------------------------------------
#16 57.57     
#16 57.57     statsmodels/tsa/kalmanf/kalman_loglike.pyx:266:55: Cannot convert 'int *' to Python object
#16 57.57     
```
at the end of these errors it says `executor failed running [/bin/sh -c pip install svtools]: exit code: 1`

**Comment by anoronh4** [comment]
i seem to have installed svtools using #300, but instead of `statsmodels==0.90` (couldn't be found in PyPI) I used `statsmodels==0.11.0` (that's the version included in `docker://halllab/svtools`). However, the svtools does not work at all. 
```
Traceback (most recent call last):
  File "/usr/local/bin/svtools", line 7, in <module>
    from svtools.cli import main
  File "/usr/local/lib/python2.7/dist-packages/svtools/cli.py", line 15, in <module>
    import svtools.sv_classifier
  File "/usr/local/lib/python2.7/dist-packages/svtools/sv_classifier.py", line 5, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.groupby import GroupBy  # noqa: F401
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby/groupby.py", line 25, in <module>
    from pandas.util._validators import validate_kwargs
  File "/usr/local/lib/python2.7/dist-packages/pandas/util/_validators.py", line 7, in <module>
    from pandas.core.dtypes.common import is_bool
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/dtypes/common.py", line 10, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/dtypes/dtypes.py", line 16, in <module>
    from .inference import is_list_like
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/dtypes/inference.py", line 9, in <module>
    from pandas.compat import (
ImportError: cannot import name Set
```
I get this even when running `svtools` with no parameters or submodules on singularity. crazily enough `/usr/local/lib/python2.7/dist-packages/pandas/core/dtypes/inference.py` does not exist within the docker image. also, when i run `svtools` with docker itself, i get:
```
# svtools
Traceback (most recent call last):
  File "/usr/local/bin/svtools", line 7, in <module>
    from svtools.cli import main
  File "/usr/local/lib/python2.7/dist-packages/svtools/cli.py", line 15, in <module>
    import svtools.sv_classifier
  File "/usr/local/lib/python2.7/dist-packages/svtools/sv_classifier.py", line 8, in <module>
    import statsmodels.formula.api as smf
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/formula/__init__.py", line 2, in <module>
    from .formulatools import handle_formula_data
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/formula/formulatools.py", line 1, in <module>
    from statsmodels.compat.python import iterkeys
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/tools.py", line 11, in <module>
    from statsmodels.tools.validation import array_like
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/validation/__init__.py", line 1, in <module>
    from .validation import (array_like, bool_like,  dict_like,
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/validation/validation.py", line 1, in <module>
    from collections.abc import Mapping
ImportError: No module named abc
```

**Comment by YourePrettyGood** [comment]
Not sure if this is the same root issue as you're having, but I was getting that `ImportError: No module named abc` error as well (on multiple clusters).  This seems to be an issue with using `statsmodels>=0.11.0` as a dependency (or rather, not constraining its version), as running the following seems to remedy the ImportError:
```bash
pip install --upgrade --force-reinstall statsmodels==0.10.2
```

It might be worth updating `setup.py` to relax the `pandas` version requirement and add a `statsmodels` version requirement (here: https://github.com/hall-lab/svtools/blob/6a6a7b059df196ec49de6cd0b8ff816942f9055a/setup.py#L34).  I went down this rabbit hole initially because pip was giving an error about `svtools` requiring `pandas==0.19.2` but `statsmodels==0.11.0` requiring `pandas>=0.21`, so fixing those version constraints ought to fix it all.

Best regards,
Patrick Reilly
