### ISSUE TITLE
lsort Index error 

### ISSUE THREAD

**Issue by stubbsrl** [hall-lab/svtools#316]
I ran the following command:
svtools lsort P001_WD11-smoove.genotyped.vcf.gz P001_WD12-smoove.genotyped.vcf.gz P001_WE11-smoove.genotyped.vcf.gz | bgzip -c > sorted.vcf.gz

And I get this error:

Traceback (most recent call last):
  File "/home/ubuntu/progs/miniconda3/envs/smoove/bin/lsort", line 70, in <module>
    sys.exit(main())
  File "/home/ubuntu/progs/miniconda3/envs/smoove/bin/lsort", line 27, in main
    samples = l_bp.parse_vcf(vcf_file_name, vcf_lines, vcf_headers)
  File "/home/ubuntu/progs/miniconda3/envs/smoove/bin/l_bp.py", line 31, in parse_vcf
    if not 'SECONDARY' in A[7]:
IndexError: list index out of range

This out of range error would suggest that there is nothing in the 7th column (using python counting) of [one of] my vcfs. This is the INFO column. My vcfs have 10 columns and I checked that none were empty. What could be some other causes of this error?

**Comment by dr-ashu-geno** [comment]
Dear @stubbsrl 

Could you solve the problem?
My VCF files all have 10 fields in non-header lines, but I still get this error message.

Any suggestions for solving the problem?

Best,

**Comment by stubbsrl** [comment]
Well it looks like I took terrible notes around that time. I posted the issue on Nov 2 and on Nov 3 I wrote down the following in my notes: 
"specify version in install and then it works
conda install svtools=0.4.0"

Unfortunately, that is all I wrote. So, I do not know if "it works" references the above problem, but I'm hoping it does. I do see that I have a few versions of svtools installed on our HPC so perhaps you need to have 0.4.0. Good luck!

**Comment by dr-ashu-geno** [comment]
Thank you for the reply.
I realized that my problem was "passing VCF files to svtools as a list in a text file". 
After passing them one by one, as you did in your command, I didn't get that error message anymore. 

I see in your command, VCF files are all smoove outputs; in my case, stools works on smoove outputs with no errors. But I am trying to merge the outputs of different programs (Manta, DELLY, smoove, CNVnator) using svtools and every time I run the program, I get a different error message related to the lack of information in other programs' outputs (other than smoove) such as lack of CIPOS, CIEND, STRAND, etc., driving me crazy!

Anyway, thank you again for the info,
Best wishes,
