### ISSUE TITLE
GT:CN ./.:309.986

### ISSUE THREAD

**Issue by pingxinxing** [hall-lab/svtools#332]
Hello, author, when I use svtools to detect sv, I found that when the classify step is allowed, it will give such an error: 
[ 
sex chromosome names are: set(['chrNC_067395.1', 'NC_067395.1'])
loading annotations
reclassifying
Traceback (most recent call last):
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/svtools-0.5.1_py27/bin/svtools", line 10, in <module>
    sys.exit(main())
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/svtools-0.5.1_py27/lib/python2.7/site-packages/svtools/cli.py", line 79, in main
    sys.exit(args.entry_point(args))
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/svtools-0.5.1_py27/lib/python2.7/site-packages/svtools/sv_classifier.py", line 661, in run_from_args
    args.diag_outfile
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/svtools-0.5.1_py27/lib/python2.7/site-packages/svtools/sv_classifier.py", line 603, in run_reclassifier
    method)
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/svtools-0.5.1_py27/lib/python2.7/site-packages/svtools/sv_classifier.py", line 487, in sv_classify
    df = load_df(var, exclude, sex, sex_chrom_names)
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/svtools-0.5.1_py27/lib/python2.7/site-packages/svtools/sv_classifier.py", line 335, in load_df
    log2r = math.log((float(cn)+epsilon)/2, 2)  # to avoid log(0)
ValueError: could not convert string to float: .    ]

After that, I observed my genotyping file. I first carried out lsort and lmerge on all individuals, and then carried out genetic analysis by using svtools genotype, and found that there were genotypes such as "./."in SV of some individuals. I thought, shouldn't there be genotypes in every SV? Why is there a situation of "./."? I don't quite understand. In addition, when calculating the copy number, some individual SV will appear "GT:CN ./.:309.986", which I think may be because of this genotype that the subsequent classify step cannot be carried out normally. But I can't find out why there is such a problem at present. Could you check it for me?

**Comment by 1455926924-ctrl** [comment]
Have you solved it yet? I had the same problem。Thanks!
